select * from CITY where CITY.POPULATION > 100000 and CITY.COUNTRYCODE = 'USA'

select NAME from CITY where CITY.POPULATION > 120000 and CITY.COUNTRYCODE = 'USA'

SELECT * FROM CITY

SELECT * FROM CITY WHERE CITY.ID LIKE '1661'

SELECT * FROM CITY WHERE CITY.COUNTRYCODE LIKE 'JPN'

SELECT C.NAME FROM CITY C WHERE C.COUNTRYCODE LIKE 'JPN'

SELECT CITY, STATE FROM STATION

SELECT DISTINCT CITY FROM STATION WHERE STATION.ID % 2 = 0

